### ISSUE TITLE
How supported will upgrading an existing site be by installing the modules?

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov#112]
Currently, Localgov works great by installing fresh as a distribution.
However installing the modules into an existing site produces errors with config. 

- https://github.com/localgovdrupal/localgov_core/issues/34
- https://github.com/localgovdrupal/localgov_services/issues/75
- https://github.com/localgovdrupal/localgov_core/issues/35
- https://github.com/localgovdrupal/localgov_paragraphs/issues/7

Whilst these can be easily fixed / bypassed, this has potential to be an ongoing problem. 
Will simply installing the modules in an existing site be seen as supported, or is the intention that site will be new builds?

**Comment by ekes** [comment]
From slack:-

_ekes  11:51_
Grep'ing code I don't think we did a bad job of following the if it's touched rename it rule [note: this was the original decision]. So most of the code written doesn't use `field_` prefixes. Paragraphs stuff comes up. Tests - but I think that's just because it's creating fields for the test.
But masses of the templating, and default content etc. does.
Which possibly highlights the biggest stumbling block, any site that has their own templating will rely on the field names, and it'll require updating all of the custom theming?

_Andy Broomfield (BHCC)  12:26_
@ekes, i thing that may have been the original discussion when building out as a distro, however it has raised issues with trying to install and use the modules in an exsting site, which is why we are now pushing for a rename of all field names.
Yes templating, and any custom themes that rely on old field names are goiing to be the largest issue, so this needs to be co-ordinated.

_ekes  12:28_
It's more a major version change. Anyone upgrading to the next version needs to rewrite their theme?

_Andy Broomfield (BHCC)  12:28_
Being able to rename the field names so BHCC can install the modules is critical if BHCC is to use the code without waiting for the distribtion to be at full release (at which point BHCC will have diverged usage quite significantly), I'm currently working on changes to the BHCC service hub (landing page) content type on the old site. It would have been prefferable to be able to make those changes within the Localgov ecosystem or at least extend those content types ourselves instead of having to work with the legacy code (edited) 

As alpha, should be ok to make this as breaking change, better to do now before beta? @ekes

_ekes  12:34_
Better done already :slightly_smiling_face: But I don't know how many existing (or almost existing) sites will need to rewrite.
So making it a major version change and still backporting security updates to the other version seems polite even if it's technically alpha.

_Andy Broomfield (BHCC)  12:40_
I think the precendent was replacing Campaigns for Sub sites which occured during the Croydon migration. Since it should only be 2 full sites (Croydon and Lambeth) and others in development (Bracknell, Hammermisth, London Councils, Cumbria?), and the change should be search and replace the issue may not be huge if done now. It should also be possible to provide the legacy field names to templates / code as a bridge in preprocess if the field does not alredy exist

**Comment by ekes** [comment]
@tanc How complicated do you think it it would be to change the field names on the theme level for Lambeth?

**Comment by tanc** [comment]
@ekes I don’t imagine it would be too hard, more of a find/replace kind of thing. Generally in Lambeth it would all be happening in the theme’s template directory where fields values are prepared and passed in as variables to the component twig templates.

To be confident nothing is missed or broken I’d want to have visual regression tests using backstop for all templates, so that would take a while to set up. But otherwise the process would be quite quick I imagine.

**Comment by andybroomfield** [comment]
What would the scope of the impact of renaming the fields from field_* to localgov_* be?

There are the fields in localgov_core that are part of localgov_services. However the update hook itself takes care of updating the config, it will still need a co-ordinated release. There is existing code to bring in this update in a [branch of localgov_services](https://github.com/localgovdrupal/localgov_services/compare/fix/75-rename-fields).
Then there is the theme, which at least localgov_services_landing_page node template will require updating if its changing the module provided one. I assume there will be other issues there but its really just search and replace as @tanc mentioned. 

So I think within project its doable to go ahead with a field rename and co-ordinate release updated accross the project.

The bigger imapace is on outside developers who have took the code. Is it feasable to ask anyone who has used it to also co-ordinate an update to their theme, and is that likley to be the only place that will be impacted. As mentioned above, it should / (would?) be possible to provide a compatability shim to so that calls to old names referenece the new field name data.

**Comment by andybroomfield** [comment]
Is the main concern from an external sites perspective twig templates?
If so, I did a quick experiment and it is possible to provide the old field names in a preprocess hook with the values from the renamed field. This will work with twig only, so any PHP logic that relies on the field name would have to be updated.

**Comment by andybroomfield** [comment]
Here is the list of effected fields.
Taken from a default Localgov Drupal install with localgov_demo module installed.

Field name | Entity type | Field type | Used in
-- | -- | -- | --
field_address | node | Text (formatted, long) (module: text) | Service landing page
field_address_first_line | node | Text (plain) (module: core) | Service landing page
field_common_tasks | node | Link (module: link) | Service pageService landing page
field_contact_us_online | node | Text (plain) (module: core) | Service landing page
field_destinations | node | Entity reference (module: core) | Service landing page
field_download_links | node | Link (module: link) | Service page
field_enable_service_updates | node | Boolean (module: core) |  
field_hearing_difficulties_phone | node | Text (plain) (module: core) | Service landing page
field_hide_related_topics | node | Boolean (module: core) | Service page
field_link_to_map | node | Link (module: link) | Service landing page
field_localgov_services_landing | node | Entity reference (module: core) |  
field_media_image | node | Entity reference (module: core) |  
field_opening_hours | node | Text (formatted, long) (module: text) | Service landing page
field_other_team_contacts | node | Text (plain) (module: core) | Service landing page
field_override_related_links | node | Boolean (module: core) | Service page
field_page_components | node | Entity reference (module: core) | Service page
field_popular_topics | node | Entity reference (module: core) | Service landing page
field_related_links | node | Link (module: link) | Service page
field_service_status | node | List (text) (module: options) | Service status
field_service_status_on_landing | node | Boolean (module: core) | Service status
field_service_status_on_list | node | Boolean (module: core) | Service status
field_topics | node | Entity reference revisions (module: entity_reference_revisions) | Service sub-landing page
field_reusable_paragraph | paragraph | Entity reference (module: core) | From library

**Comment by andybroomfield** [comment]
This piece of work is done.
