### ISSUE TITLE
Document how to add these modules to a monorepo setup

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov#114]
Making note here for now.
When installing these modules into a site, as they are not releases yet, Composer will clone the git repo. This is fine for setups which use Composer to build the sites. However some legacy sites, and some hosting providers (Acquia / Pantheon), require all dependencies to be commited into Git in order to deploy to hosting.

This causes issues with Git as it now assumes your trying to add a submodule.
> warning: adding embedded git repository: docroot/modules/contrib/localgov_alert_banner
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint: 
hint: 	git submodule add <url> docroot/modules/contrib/localgov_alert_banner
hint: 
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint: 
hint: 	git rm --cached docroot/modules/contrib/localgov_alert_banner
hint: 
hint: See "git help submodule" for more information.

The workaround is to use the `--prefer-dist` option in composer, which for Github hosted modules downloads a package .zip. or adding the following to composer.json. 
````json
"config": {
    "preferred-install": {
      "localgovdrupal/*": "dist"
    }
  },
````
See : https://getcomposer.org/doc/06-config.md#preferred-install.

**Comment by finnlewis** [comment]
@andybroomfield recently I've noted that installing from fresh does not include the git repos for all projects.

This might be something that changed since tagging with 1.0.0-alpha1 I wonder.

Either way, we should document the process... which reminds me that we need to start something more accessible for documetation.

**Comment by andybroomfield** [comment]
@finnlewis yes, now there's tag releases, composer will download the .zip that's published on the releases page.

**Comment by Adnan-cds** [comment]
This has caused me and Chris some confusion recently.  When we ran *git log* inside localgov_theme of our local LocalGov site, we thought we are seeing the log for localgov_theme, but it was really from our LocalGov Croydon codebase as localgov_theme wasn't carrying any Git repository info.

I just tried something similar to what Andy has mentioned above and now all LocalGov modules and themes are pointing to their own Git repo:
```
$ git clone git@github.com:localgovdrupal/localgov_project.git
$ cd localgov_project/
$ composer config preferred-install."localgovdrupal/*" source
$ composer install
```
This seems to be useful only to those who want to develop LocalGov Drupal further rather than anyone who downloads LocalGov Drupal.  This means we shouldn't update the localgov-project template, but perhaps we can document it for LocalGov Drupal developers.

FAO @finnlewis @andybroomfield @cjstevens78 @stephen-cox

**Comment by andybroomfield** [comment]
I'll take a look at this and add to the docs, though as we have releases now this issue is moot, and if your using git branches directly and a mono repo we assume you know what you are doing. 
For what its worth, a build tool like [Acquia-BLT](https://docs.acquia.com/blt/) is the direction to head which does mean maintaing a seperate develop and deploy repo, however that does give less headaches.

**Comment by andybroomfield** [comment]
All I can say is, "rather you than me!" (to myself, having once attempted this).
I'm going to close as not required now all modules have releases they will download as .zip files and be installed without the git sub repo. For patches / dev versions it will be a bit different and I assume anyone still brave enough to try it the mono repo way knows what they are doing.

Happy to reopen if anyone feels this is needed.
