### ISSUE TITLE
Documentation - set up a place for all the docs

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#149]
The lack of documentation is becoming an issue. We really need a simple way to publish documentation somewhere for people to be able to understand a) what LocalGov Drupal does, b) how to install or make use of it c) how to get involved and contribute.
@paulpopus do you have some ideas of what to use?

**Comment by andybroomfield** [comment]
It would be nice to use localgovdrupal to itself host the documentation if possible (might be a strech).
Short term may be a hugo or tome based static site hosted out to netlify.

**Comment by paulpopus** [comment]
I would want to use [Vuepress](https://vuepress.vuejs.org/guide/) and set it up with auto builds on github, maybe netlify or one of our own servers.

I don't like the idea of using localgovdrupal to host the documentation because of content editing, markdown is easier over wysiwyg when dealing with code and technical info and having to maintain a CMS just so it can serve static files. Setup would also require more time I reckon.

**Comment by finnlewis** [comment]
I think keep it simple for now, rather than trying to host the docs on a LGD site. 

Something that can be hosted for free, I'd come across: 
 - https://docusaurus.io/
 - https://readthedocs.org/

It looks like VuePress can also be hosted for free, great!

I don't really mind as long as it is : 
 - easy to contribute documentation to
 - free to host - forever
 - is readable / accessible

**Comment by andybroomfield** [comment]
[We have this now](https://localgovdrupal.org)! Yeah! So closing.
