### ISSUE TITLE
Tests failing with composer 2

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov#152]
Is there a way we can pin this back to use composer 1 for now?

Getting errors when testing pull requests into localgov_services.
The tests exit after 30 seconds.
````
You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
67
Error: Process completed with exit code 2.
````

**Comment by finnlewis** [comment]
Me too @andybroomfield 

I've been trying to untangle the dependencies to get it working with composer 2, no joy as yet.

**Comment by finnlewis** [comment]
Guessing it's this line if we want to install composer 1.x

https://github.com/localgovdrupal/drupal-container/blob/master/Dockerfile#L56

**Comment by finnlewis** [comment]
I tried this, it didn't work: 
https://github.com/localgovdrupal/drupal-container/pull/10

**Comment by stephen-cox** [comment]
This issue was fixed here https://github.com/localgovdrupal/drupal-container/pull/10 but installing Composer v1 in to the Docker container and using this to run any composer operations. The problem with this solution is that we need to update the Github CI configuration for all repos. 

Unfortunately, I'm not aware of a way to fix this problem without making some changes to all the GitHub Ci config. @Adnan-cds points to some workarounds here: https://github.com/actions/virtual-environments/issues/1924, but they will still need changes to all Github CI config files.

The advantage of using the version installed in the Docker container used to run the tests is we can use Composer 2 later on without having to make changes to all the Github CI later on: https://github.com/localgovdrupal/drupal-container/blob/847d8773550bcdb3dea22b9037f536ff5563fcd7/Dockerfile#L56

The disadvantage being is maybe quite a bit slower, although if this is a concern we should benchmark this.

**Comment by Adnan-cds** [comment]
> The disadvantage being is maybe quite a bit slower, although if this is a concern we should benchmark this.

I have tried to compile a list below for the three available options:
- Install composer v1 in our Docker container and use it to do "composer create-project": [5min 52sec](https://github.com/localgovdrupal/localgov_directories/runs/1341576198?check_suite_focus=true#step:4:1)
- Install composer v1 using the shivammathur/setup-php@v2 action and then do "composer create-project" as before: [2min 43sec including the time to switch to composer v1](https://github.com/localgovdrupal/localgov_directories/runs/1333388101?check_suite_focus=true#step:4:1)
- Use composer v1 provided by the build VM (no longer available): [1min 31sec](https://github.com/localgovdrupal/localgov_directories/runs/1193335123?check_suite_focus=true#step:3:1)

So clearly, the one from the build VM performs best.  This leaves us with two **future** options:
- As soon as drupal/console-extend-plugin is fixed, switch to the composer v2 that ships with the build VM.
- Drop "drupal/console" from the localgovdrupal/localgov [profile](https://github.com/localgovdrupal/localgov/blob/f3756ce8c792030a3fa2f14dd56ff0edc6e37198/composer.json#L16) and enjoy composer v2.

**Comment by stephen-cox** [comment]
If this is only an issue with drupal/console then I vote to drop it until it supports Composer v2.

**Comment by Adnan-cds** [comment]
> If this is only an issue with drupal/console then I vote to drop it until it supports Composer v2.

Apart from drupal/console, we also need to tell the localgov_project's [composer.json](https://github.com/localgovdrupal/localgov_project/blob/0d0bd98cee005831d9dcb64bf2fdf91a2cedfeb7/composer.json#L18) to use "drupal/core*: ^8.9.7" but that should be easy.

I was thinking perhaps we can make *drupal/console* a [suggested](https://getcomposer.org/doc/04-schema.md#suggest) package of localgovdrupal/localgov rather than a required one.

**Comment by stephen-cox** [comment]
For reference, this is the issue that will add Composer 2 support to Drupal Console https://github.com/hechoendrupal/drupal-console-extend-plugin/issues/23 and this is the pull request https://github.com/hechoendrupal/drupal-console-extend-plugin/pull/25

**Comment by finnlewis** [comment]
Following your suggestions @stephen-cox and @Adnan-cds - I've tested removing drupal/console and upping core to 8.9.
This seems to work, as @Adnan-cds suggested.

Here's a couple of PRs to help test it: 

https://github.com/localgovdrupal/localgov/pull/153
https://github.com/localgovdrupal/localgov_project/pull/28

What do you think?

**Comment by finnlewis** [comment]
Oooh - this is good: https://www.drupal.org/docs/develop/using-composer/preparing-your-site-for-composer-2
Perhaps we should run through the recommendations there too.

**Comment by Adnan-cds** [comment]
> https://www.drupal.org/docs/develop/using-composer/preparing-your-site-for-composer-2

Useful link.  Thanks a lot.

We are using two Composer plugins from the given [list](https://www.drupal.org/docs/develop/using-composer/preparing-your-site-for-composer-2#s-upgrade-the-following-plugins-to-a-version-of-the-plugin-that-supports-composer) AFAIK:
- composer/installers: "drupal/core-recommended: ^8.9.7" should take care of it.
- drupal/console-extend-plugin: This you have dropped in a different pull request.

So looks like we should be good :)

**Comment by Adnan-cds** [comment]
I am having that "Back on the road feeling": https://github.com/localgovdrupal/localgov/runs/1354189654 :D

The "Create LocalGovDrupal project" task has finished in **1min 15sec** under Composer 2 which is neither an improvement nor a loss.
