### ISSUE TITLE
Write release notes for the pending release. 

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#187]
This is for the field rename release next week.

**Comment by andybroomfield** [comment]
These modules and theme update will update the field machine names used in the service landing, sub landing, service page and the page components paragraph. This also renames references to those fields in localgov theme.

The following fields machine names will be updated:
````
field_email_address              to localgov_email_address
field_facebook                   to localgov_facebook
field_phone                      to localgov_phone
field_twitter                    to localgov_twitter
field_page_components            to localgov_page_components
field_address_first_line         to localgov_address_first_line
field_address                    to localgov_address
field_contact_us_online          to localgov_contact_us_online
field_destinations               to localgov_destination
field_hearing_difficulties_phone to localgov_hearing_difficulties_ph
field_link_to_map                to localgov_link_to_map
field_opening_hours              to localgov_opening_hours
field_other_team_contacts        to localgov_other_team_contacts
field_popular_topics             to localgov_popular_topics
field_common_tasks               to localgov_common_tasks
field_download_links             to localgov_download_links
field_hide_related_topics        to localgov_hide_related_topics
field_override_related_links     to localgov_override_related_links
field_related_links              to localgov_related_links
field_service_status_on_list     to localgov_service_status_on_list
field_enable_service_updates     to localgov_enable_service_updates
field_service_status             to localgov_service_status
field_service_status_on_landing  to localgov_service_status_on_landi
field_topics                     to localgov_topics
````

Before you begin, make sure you have a complete back up of your sites code, files and database as these updates cannot be rolled back once applied. You should also export and commit your current config as part of the update process involves exporting and reimporting the sites config to get the renamed field names to stick.

Update to these modules using composer update. It is important to update to the latest releases of localgov_core, localgov_services, localgov_page_components and localgov_theme at the same time.

Next run the database updates. Run the database updates either by visiting yoursite.com/update.php or using the command drush updb. This will go through each module and rename the fields used by each module.

Once database updates have been run, you must export your config (eg. using drush cex) and commit your config to version control. This is so that the changed field names are preserved in your site. Then import the config using drush cim which will remove any last references to the old field name. 

If you import the old site config before exporting it, the old field names will be resurrected. If this happens you will need to manually change the database installed version and re-run the database updates for that module.

After applying these updates, check your sites theme and custom modules for any references to the old field names and search and replace them. Test the site to check for all data is present and fields are displaying correctly. Then commit and deploy the update.

To keep your current versions if you are not ready to update yet, add the following to your root composer.json and run composer update.

````
"localgovdrupal/localgov_core": "1.0.0-alpha2",
"localgovdrupal/localgov_services": "1.0.0-alpha2",
"localgovdrupal/localgov_page_components": "1.0.0-alpha1",
"localgovdrupal/localgov_theme": "1.0.0-alpha3"
````

This will prevent these modules and theme being updated, however to get future updates you will need to proceed with the update.
