### ISSUE TITLE
Theme architecture - overview and proposal for changes

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#192]
Creating this issue to track the proposal, decision and plan for imrpoving the overarching front-end architecture.

(Hoping this is not a duplicate, but please flag if it is)

@markconroy has come with a fresh pair of eyes to the LocalGov Drupal project and has been reviewing code and making suggestions. This has evolved into a proposal to evolve the templating and css assumptions and create a new base theme.

The current proposal is at https://docs.google.com/document/d/1b3M3XnRYXlzqLdq05s4hE3AlzoNQP-89OKXXx3FleEQ/edit#

@markconroy currently estimates about three sprints of work, but I guess this will depend on the work to do and the resources available to assist with the work. 

Personally I think this sounds like a positive direction to take the fron-end architecture, so we need to make sure everyone has had a chance to understand the motiviations, proposed changes and has the opportunity to raise any concerns before accepting this into sprint 11 starting on 28th April.

For anyone interested, please could you confirm:

1. Have you read the proposal linked to above?
2. Do you have any questions to clarify the proposal? 
3. Do you have any critifcal concerns about the proposal? 

Other comments also welcome.

CC @andybroomfield @Adnan-cds @cjstevens78 @markconroy @ekes @stephen-cox @msayoung @tanc @ReeceMarsland @danchamp @gosia-mlynarczyk @willguv @tom-steel

**Comment by willguv** [comment]
@finnlewis thanks. I'm tracking down the current councils using the default theme and will keep you posted

**Comment by markconroy** [comment]
@willguv as part of that process, can you see how many councils are using Skeleton as their base as well? I have a feeling some might be using skeleton but not localgov_theme. Thanks.

**Comment by willguv** [comment]
@markconroy that's many more councils, possibly all. I'll find out

**Comment by markconroy** [comment]
That might help, though just because a theme is enabled on the live site, doesn't mean it's being used as a base theme. Most sites will have Bartik enabled, but not being used.

**Comment by andybroomfield** [comment]
This discussion had me thinking about Terenced Ednets post on how someone was able to use the [Gov uk Hosing benefift pages on a PlayStation Portalble](https://shkspr.mobi/blog/2021/01/the-unreasonable-effectiveness-of-simple-html/). 

Whilst I appreciate the move to more modern design, its also important to make sure that even if its a crappy browser that key information works. Doesn't have to be be pixel perfect, fallback is fine. We need to support all citizens, even if there equipment is not the most up to date.

I'm going to ask to see what the anayltics say about browseer use on BHCC.

**Comment by cjstevens78** [comment]
At Croydon we have taken the ‘localgov_theme’ and used it as a base and have our own theme ‘localgov_theme_croydon’ which adds to or overrides elements of the localgov theme to provide theming for elements that are unique to Croydon. I have concerns about how changes within localgov_theme will impact Croydon - we have some templates files copied out to our theme but many are pulled in from the modules themselves or templates within localgov_theme - if the html in the templates changes or the class naming structure changes, use of JS etc in the theme - then presumably there will be time and effort (and expense) involved to get Croydon rendering and functioning correctly.

**Comment by markconroy** [comment]
Hi @cjstevens78 

The aim will be to disrupt current sites as little as possible. Some options I am thinking of - and please drop in any other options you think off too - include:

- Move templates/CSS/JS from modules to skeleton, and then since your theme is using Skeleton as a base, everything will continue to work, and/or
- rewrite the templates inside the module (which will affect classes and layout), which will follow Drupal standards, and also rewrite the CSS to use these new classes, and/or
- move all templates to the new theme, so anyone looking for a template in future will know where to find them, and/or
- set the new theme as the base theme of Skeleton, so in the future if any new templates are added to the base them Skeleton (and all themes that use that) will also have those templates available, and/or
- Spending time with each council to help them fix up any issues that we may have created (hopefully not many), and/or
- whatever other options get proposed to solve this

I think localgov_services might be a good item to start with, since that is used as part of localgov_core. We can then see what issues that throws up and what might need to be solved before we work on the rest of the issues

**Comment by finnlewis** [comment]
Just looking at this as it is assigned to me and on the beta project board. I think we can close this as the discussion was had and we're proceeding with the refactoring of the [localgov_base theme](https://github.com/localgovdrupal/localgov_base) with the working group guiding and reviewing the work.
