### ISSUE TITLE
Agree the release tagging policy with the technical group.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#198]

**Comment by ekes** [comment]
Suggested text:-

https://github.com/localgovdrupal/localgov/wiki/Versioning

The Semantic Versioning, including not using patch versions in profile (production) code, comes from the discussions in the Tech Group and documented on https://github.com/localgovdrupal/localgov/issues/139#
The fact that versions are created by making a Merge Request from master into the release branch seems to be practice but not documented. This to me works for making the decision explicit - except for some of the 1.0.0 versions that I am tagging with no new code so there is no PR to be made - I made an issue.
The involvement outside tech/github in larger releases s also a description of practice rather than anything codified so far.

**Comment by ekes** [comment]
@finnlewis @danchamp @Adnan-cds @andybroomfield @stephen-cox (tagging you as involved in the original discussion, but everyone).

Does that :point_up: correlate with what you think was agreed and is current practice?

**Comment by stephen-cox** [comment]
I think that wiki page is fine. It would be useful to include something on how to do a release (PR into release branch, change log and notes), but that can be considered elsewhere.

**Comment by finnlewis** [comment]
Thanks @ekes @stephen-cox 

I've expanded on the releae process to be a little more specific, does it sound correct?

https://github.com/localgovdrupal/localgov/wiki/Versioning

**Comment by ekes** [comment]
First up. Discussions about releasing 2.x versions have now certainly followed the practice we've codified in the wiki. Some of the discussion thread from https://github.com/localgovdrupal/localgov/pull/212#discussion_r628731461

Second policy that is developing. To support composer's defaulting to a development branch with a similar pattern to the releases: 1.x, or 1.2.x branch names for 1.2.* development versions. Suggest adding:-

"When appropriate more than one major version of the modules or the profile will be maintained.
"Development for versions is merged into their composer closest name branch. Presently 1.x and 2.x
"Releases are made by requesting a Merge Request from the relevant development branch into the related release branch: eg 1.x into 1.x-release; 2.x into 2.x release

**Comment by finnlewis** [comment]
From work this sprint, discussions in Slack, and discussions at standups, I think we can call this is agreed. 

Any critical concerns?

**Comment by ekes** [comment]
Updated the wiki.

Last question:

1.x/release
release/1.x
1.x-release
release-1.x

I'd actually rule out 1.x-release as it's confusing the release with pre-release identifiers (-alpha etc.)

**Comment by stephen-cox** [comment]
Not sure it makes much difference, but my vote is for `release/1.x`

**Comment by stephen-cox** [comment]
Just tried renaming the release branch in topics to `release/1.x` and this gets rejected as an invalid branch name. Have gone with `release-1.x`, but we can change this if we want.

**Comment by finnlewis** [comment]
Updated https://github.com/localgovdrupal/localgov/wiki/Versioning#release-branch-naming

I think this can be closed
