### ISSUE TITLE
Decide the preferred options for scheduling in Drupal 8/9 - Scheduler vs Scheduled transitions

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#242]
@ekes @andybroomfield 

We need to provide a summary of how these two approaches work.

We are hoping to form a working group to meet next Friday.

@ekes would you be able to summarise the differences and implications?

**Comment by ekes** [comment]
# Scheduled Transitions

 * Works only with workflow. So you need workflow transitions (publish, unpublish) to make it work.
 * Works with any entity as it is actually scheduling the workflow transition action.
 * Can then set the permissions at high granularity ![Screenshot_2021-06-07 Permissions Drush Site-Install](https://user-images.githubusercontent.com/237186/121064199-8d6bbe80-c7c7-11eb-8c3e-160ecf9a9246.png)
 * Enabled per content type with a workflow the scheduling is done on a tab of each piece of content ![Screenshot_2021-06-07 Service page to schedule Drush Site-Install](https://user-images.githubusercontent.com/237186/121064187-8ba1fb00-c7c7-11eb-8e95-40dd75184b38.png) The tab lets you view and add transitions ![Screenshot_2021-06-07 Scheduled transitions Drush Site-Install](https://user-images.githubusercontent.com/237186/121064196-8cd32800-c7c7-11eb-9bcc-490d0876ee1b.png)
 * When you create a new transition you set from which version to what state ![Screenshot_2021-06-07 Scheduled transitions Drush Site-Install(1)](https://user-images.githubusercontent.com/237186/121064194-8c3a9180-c7c7-11eb-9b6c-0fbe346d9cb6.png) This might not be the most obvious thing for people to use. It is powerful: you can set the current version to published, or unpublished (obvious) but also a new draft version to replace the existing version (so changing live content). ![Screenshot_2021-06-07 Scheduled transitions Drush Site-Install(2)](https://user-images.githubusercontent.com/237186/121064192-8c3a9180-c7c7-11eb-869e-9d97f651536e.png)
 * In addition to the tab on the user there is a 'Scheduled content' list page that shows an overview of all scheduled content. ![Screenshot_2021-06-07 Scheduled Transitions Drush Site-Install](https://user-images.githubusercontent.com/237186/121064180-893fa100-c7c7-11eb-8a2a-2c3dee1877c1.png)
 * Scheduled transitions themselves are entities - probably a reason for opting to put them on a tab rather than on the form (but inline entity form?). Gives the easy view listing everything scheduled.
 * Translation support: to be confirmed but seems you can choose to schedule by revision, or the translation.

# Scheduler 

 * By default does not work with workflow. There is an additional module to add workflow support.
 * Patch looking good for integration to make it work with any entity.
 * Scheduler is enabled on a content type ![Screenshot_2021-06-07 Edit Service page content type Drush Site-Install](https://user-images.githubusercontent.com/237186/121064183-8a70ce00-c7c7-11eb-89c5-0c36cedd177c.png) Choice is allowing publish or/and unpublish.
 * Permissions to schedule changes are per content type
![Screenshot_2021-06-07 Permissions Drush Site-Install(1)](https://user-images.githubusercontent.com/237186/121065705-59919880-c7c9-11eb-8a75-f0c4639fddb2.png) Workflow support does not add additional options.
 * Without workflow it offers a straightforward field on the form for time of un/publish ![Screenshot_2021-06-07 Create Guide overview Drush Site-Install](https://user-images.githubusercontent.com/237186/121064185-8b096480-c7c7-11eb-92d3-3e87d831be73.png) 
 * With workflow it offers the states to move to ![Screenshot_2021-06-07 Edit Service page Published content to be unpublished Drush Site-Install](https://user-images.githubusercontent.com/237186/121064181-8a70ce00-c7c7-11eb-9342-bd048277e3fc.png) There seems to be no permissions control over which particular published/unpublished states users can move from to. This example also hadn't picked up the unpublished state.
 * Adds database columns to the entity_field_data (and entity_field_revision) for publish_on, unpublish_on and with workflow support publish_state, unpublish_state.
 * Translation support: each revisions, and translation, must be scheduled separately. Seems a bit buggy too https://www.drupal.org/project/scheduler/issues/3080979 which might also relate to the issues mentioned with workflow to unpublished.

**Comment by andybroomfield** [comment]
Basically as @ekes summary. I would say that scheduler is simpler from a content designer perspective in that the publish and unpublish dates are right on the form. Would there be value in scheduling additional states like review?
Theres a few technical advantages to scheduled transitions in that it uses its own database table instead of having the extra columns on the entity base table.
Using scheduled transitions would require all entities (like alert banner) to have workflow which could complicate things.
The fix for scheduler does work now with the patch for custom entities.

**Comment by ekes** [comment]
> Would there be value in scheduling additional states like review?

I doubt it, but both do allow for it scheduler does this with the workflow add on module. 

On that complexity I think it's more likely that you'd want to schedule a new revision to update the existing published page. There are some open issues about this for Scheduler. Permissions there also don't seem to be implemented (so a user who can't make the transition can schedule it - reading the code it should be working and checking)? My install also didn't seem to list the unpublished Archive state for making the transition to unpublish from a currently unpublished item that is scheduled to be published.

> I would say that scheduler is simpler from a content designer perspective in that the publish and unpublish dates are right on the form

For the (non-workflow) number one use case: Publish | Unpublish - this is absolutely the case. Having to go to the scheduling tab, and then comprehending it, is not content admin friendly.

**Comment by finnlewis** [comment]
We need to make a call on this to allow workflow scheduling. 

@ekes mentioned the translations issue.

I we can confirm the preferred technical approach, with any caveats, we can the move on with https://github.com/localgovdrupal/localgov_core/issues/96

@stephen-cox @ekes over to you!

Demo anything we can at Friday's working group meeting would be fab!

**Comment by stephen-cox** [comment]
I have installed both these modules on the test site.

I have setup a coupe of pages in different languages to publish at different times. Neither seem to handle the scheduling of translations properly. Scheduling the main language to publish before the translation, published both versions, even though it's possible to schedule different times on each translation.

From https://github.com/localgovdrupal/localgov_core/issues/96 the requirements for this are:

1. scheduling a new page to go live
2. scheduling a new draft to an existing page to go live
3. scheduling content to unpublish
4. scheduling a reversion to a previous revision*

Scheduler certainly does 1 and 3. A quick test shows it will publish a draft at a given time, so looks like it will handle 3. There is no option to publish a specific revision at a given time.

Scheduled Transitions looks to handle all 4 cases.

**Comment by ekes** [comment]
>> scheduling content to unpublish
> A quick test shows it will publish a draft at a given time, so looks like it will handle 3. 

To double-check this. It was what I had difficulty with above:- I could schedule from draft -> published; but while it was in draft I couldn't schedule published and then that to archived - so basically before going live setting both. This does work without workflow in scheduler, just doing published/unpublished.

**Comment by ekes** [comment]
Scheduler issue with translations:-
https://www.drupal.org/project/scheduler_content_moderation_integration/issues/3032918

**Comment by ekes** [comment]
> Scheduler issue with translations:-
> https://www.drupal.org/project/scheduler_content_moderation_integration/issues/3032918

I've not been able to repeat this with scheduled_transitions. Wondered if it wasn't something about latest revision, but not that either. Transitions are scheduled by revision & language. 
The issue here might actually be that you _have_ to schedule the transitions per language. Although duplicating the transition for a language seems trivial.

**Comment by danchamp** [comment]
> To double-check this. It was what I had difficulty with above:- I could schedule from draft -> published; but while it was in draft I couldn't schedule published and then that to archived - so basically before going live setting both. This does work without workflow in scheduler, just doing published/unpublished.

We use Scheduler on a couple of client sites and it doesn't support anything other than toggling published/unpublished.

There was a sub-module in development at one point to provide more state transitions with Content Moderation but it was never released.

**Comment by stephen-cox** [comment]
Having discussed this with @ekes  and the Content Workflow Working Group the decision has been made to go with Scheduled Transitions rather than Scheduler.
