### ISSUE TITLE
Shared fields: address

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov#39]
Directory and Services share the functionality of having addresses on them.

Directory has a field for the first line of the address, and an address field (slightly customized).
Services has a field for the first line of the address, and an text field for address.

Looking at usage in the db I have it's minimal on Services; and the shared field isn't used on the directory items.

 * Should the slightly customized addressfield become available to all localgov modules?
 * Should services rather use the addressfield? Or is it too constraining?
 * The first line doesn't make sense with addressfield - it has a 'locally known as' or 'first line' depending on which it is intended for.

**Comment by ekes** [comment]
@willcallaghan Guess you have overview of this?
@bhccwebmaster and at Brighton now?

I'm expecting there will be more of these as I fix localgovdrupal/localgov_services#15 - while it'll slow getting services modules up I think it's good to make the right choices now (if we can - if not we change them later - but rather now).

**Comment by andybroomfield** [comment]
Theres a lot to untangle here so its probbly worth setting a course for where we want to go rather than trying to rationalise a lot of past dev.

An address field makes sense, could be the standard address field from [drupal/address](https://www.drupal.org/project/address). However this doesn't always display or capture the right information a service would need, such as an address might not be a building, but the center of a park or location on the beach (public toilets is the most problematic one here when importing into a directory). Certian templates need to take out the first line (eg. Cityclean) and use that as a header for the address, which is usuallt the service corportate name, that could be something for formatting.

Croydon also have a custom contact block paragraph that may be better suited here as a replacement, if one coporate departments provide a different services (BHCC does not have this).

Where it gets more complicated is geolocation and links to map. For services this is a simple link field, though being able to display a geocoded map may potentionally be useful. For directories we do handle geocoding, this is through our own internal BHCC lookup service. Ideally this could be replaced with standard address field, however for directory editors who are usually non tech trained, they require a postcode lookup service. For BHCC this is likly to be our own internal central hub ([example on parking zones page](https://new.brighton-hove.gov.uk/parking-zones) [only works with Brighton and Hove addresses) so for BHCC is something we'd swap out. Theres also complication there in that all council geodata at BHCC and potenailly others is in OS National Grid not Lat / Long. 

I'd consider the geocoding seperate for now and rationalise the address field within service. May need to go back to comms team / services to get the display format that need to be used.

**Comment by ekes** [comment]
I also have a love hate relationship with the address module.

For now I'm going to put the address fields for services landing _only_ on the services landing content type. As it's free text on the services content type (and yes a link on map url in a separate field).

Then this issue can stay open and broaden into what the desired behaviour is actually for addresses generally, and user stories specifically for interacting with them on services and directory.

**Comment by andybroomfield** [comment]
I'm going to close this for now as I think address has settled on the address module and localgov_geo and the plain text version for service pages. Please reopen if there is any further discussion.
