### ISSUE TITLE
Proposal: Move developer documentation to Wikis in Github

### ISSUE THREAD

**Issue by aaronhirtenstein** [localgovdrupal/localgov#461]
We are looking to reduce the barrier to entry for contribution (especially non-code contributors). Currently, technical documentation sits in two places (Github Wiki  and Docs) and the current Docs site is only editable by people with a Github account. This makes it hard for people to know where to find things and for non-developers to easily contribute to documentation.

There are [a few options we could take to resolve this](https://docs.google.com/document/d/10CwN7h05dEzZi3jen2AwPYLOHDh5OLaM1_8-_IWL1Y8/edit#) and after some reflection and conversations, the simplest first step seems to be to move developer / technical documentation to Wikis in Github on a per repo basis, with clear signposting from the current Docs site (i.e. Keep [the Developer page](https://docs.localgovdrupal.org/devs/)).

**Proposal**: We propose to move technical / developer documentation to wikis on Github and signpost clearly from the main Docs site. Everything else is kept on a separate wiki.

This issue is intended to gather questions, comments and suggestion from the community so we can make a decision.

**Comment by msayoung** [comment]
Hi @aaronhirtenstein 

Thanks for this proposal. 

I am supportive in principle - anything that lowers the barrier to good and accurate documentation is a great idea - however there are a couple of thoughts. 

1. Those wikis all require a Github account to edit (at present) 
2. We'll need to think of a strategy for documenting some cross-repo features

Developer documentation that I am aware of
- Everything within: https://docs.localgovdrupal.org/devs/
- https://docs.localgovdrupal.org/accessibility/
- https://github.com/localgovdrupal/localgov/wiki
- All the project READMEs

**Comment by andybroomfield** [comment]
It's not clear how moving to wikis makes this easier to contribute than what we have currently.

This change would mean instead of having one central place to look up documentation (the docs site) it would be spread accross 50+ repositiries and you'd have to find the right one.

Sometimes its not clear which project documentation may belong to, some of the modules (localgov_paragraphs, localgov_geo) are only really useful when combined with another module (either subsites, microsites, directories etc...)

The documentation on docs.localgovdrupal.org has a nice [Help us improve this page!](https://github.com/localgovdrupal/docs/edit/master/docs/src/devs/index.md) (opens new window) which opens directly to an edit page in Github. I was able to contribute a small edit easily so aside from the Github login barrier, which as discussed above is also present for wikis, that allows for direct contribution if someone spots an issue.

Theres also the advantage of having a central place for devs and others who need to refer to technical documentation having a known single place to go.

**Comment by aaronhirtenstein** [comment]
Some thoughts from Michael Wignall on this which he said I could share - he helped put together a lot of the docs site together with @msayoung last year (I believe that's accurate):

Something needs to be done, but I'm not sure about using Github, and have general concerns about wikis.
Initial thoughts:
In terms of IA do we have a clear idea about:

- who will actually be adding or updating docs / info
- the different levels of information i.e. overview, what features do, using features, example deployments, install, module configuration, other technical deployment, contributed modules, contributed configuration (i.e. Council X has used directories in this particular way), technical issues, bugs & troubleshooting
- who those different levels are aimed at and how they fit together
- come January, who will be responding to issues / questions and who will curate and update the Wiki

There's a clear need to improve the technical documentation / updates for different audiences, and a problem around documenting anything that councils have done outside of the core install e.g. Forms, directories.
There is also still core Docs content that hasn't been written, as we either have to buy Agile time or ask councils for info and then edit it.
The original idea was to move the Docs into the main site, as it mainly consists of curated how-to guides, with some links to curated Google doc how-tos. The docs site is a pain to edit, but we have had zero interest in anyone contributing to the docs. Github itself is not user-friendly.

**Comment by aaronhirtenstein** [comment]
thanks for adding your thoughts @andybroomfield 

I agree it is not a simple fix and the proposal may not solve all the issues. One of the key motivations was to lower the barrier for non-developers to contribute documentation, I take your point about the improve this page link, but I don't think this helps people add new pages. I reckon we can get over the github login question via clearer onboarding steps (or even some onboarding steps!).
Duplicating documentation causes issues for less experienced people (either as a dev or in LGD itself), in particular, but I don't have an answer for the fact there are 56 (?) repos and documentation may relate to one or more of them!

Is it possible to have a central wiki in github for all the main info (overview, installation, what features do, example deployments etc) and then use READMEs and wikis on specific repos?

**Comment by aaronhirtenstein** [comment]
OK so we've been doing a bit of thinking about this in light of the understandable concerns of splitting dev documentation. 

We are thinking that Gitbook might meet a number of current needs: super easy to edit, no need for github account (google or emial logins possible), free (for open source projects), permissions/editorial workflow and keeps everything in one place. 

As a test to see how easy it would be to migrate things over, @dajbelshaw er migrated things over as it's dead simple: https://localgov-drupal.gitbook.io/welcome-to-gitbook/46M9hFIV2C887phv8ta2/ 

He also recorded a quick Loom video explaining the rationale and editorial process: https://www.loom.com/share/cfd76eaec7a245d481a4e79f10c816fc 

@andybroomfield how does that sound to you? And others too of course!

**Comment by finnlewis** [comment]
Discussion from Tech Drop-in today: 

- Andy: why? If we’re going to move it, we should move it to one place. Consolidate rather than spread it out
- Maria: There are docs in each project, readmes etc. 
- Rupert: I like docs in a repo - the docs can then follow the code. We could maybe have a way to consolidate separate docs into one place. 
- Maria: I’m strongly ambivalent about whether it should be all together in one place or in separate places. I really DON’T think it should be in Drupal site! Version control ++
- Ekes: There are two types of documentation: one that should be curated and book like and easy to read for newcomers. The ‘drupal.org book’ suggestion is not such daft idea for. The second type is more specific to the project / repo: README or inline code comments. 
- Stephen: We don’t want it in Drupal! The motivation is for newcomers. Where do you start? The docs site is kind of what this does at the moment. 
-  - If we agree on a format for the README.md files that always linked to the docs site index. 
- Nicolas: I always look at README.md first. 
- Justine: kind of agreeing with Maria - having docs

**Comment by aaronhirtenstein** [comment]
@msayoung @finnlewis @stephen-cox @andybroomfield @ekes 

Sorry folks I think my last comment was unclear. The Gitbook idea is to keep things in one place, not split out Dev docs into a separate place.

Gitbook enables non-technical people to contribute more easily than current docs site through better editorial process and not needing a github account to contribute.

**Comment by aaronhirtenstein** [comment]
Gonna close this issue as I think the proposal has changed
