### ISSUE TITLE
Changes councils have made to LocalGov Drupal

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#516]
We know a little about the changes that councils make to LGD as they adopt it, and it would be useful for our info to be more detailed

Let's start by talking about changes that the Backlog group has made or is considering

We can then widen to the wider group of councils

**Comment by keelanfh** [comment]
Worth giving a quick summary from Essex, even though you're probably aware of most:

## Modules
* [Content ownership module](https://github.com/essexcountycouncil/content_ownership) - for marking a stakeholder responsible for specific pages (not a Drupal user)
* [Azure B2C module](https://www.drupal.org/sandbox/matthewwilkes/3352177) - for our single sign-on integration

## CMS experience
* Changes to layout of content editing pages - removing tabbed layouts and unused fields
* Permissions changes, using the permissions model to remove content types that we're not using at the moment, but so that we can easily add them later, or an admin can try them out without getting in the way of content designers
* Using the contact component wherever possible
* Search fields to allow people to search by author of the content and last editor of the content (though we're not too sure about the interaction of this)
* Non-publishable notes - another field to add notes that aren't shown to the public. Again, not perfect and the terminology isn't right

Doesn't sound like a lot, but I think most other little things have already been done in core.

**Comment by willguv** [comment]
Thanks @keelanfh would be great to see screenshots of the non tabbed layouts. Let's chat about the other ones too

**Comment by keelanfh** [comment]
> Thanks @keelanfh would be great to see screenshots of the non tabbed layouts. Let's chat about the other ones too

Added some in #487

**Comment by willguv** [comment]
We've got a better list from the recent Community Meetup, so closing this
