### ISSUE TITLE
Drupal 10 install "Adding non-existent permissions to a role is not allowed"

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#531]
Just testing this for the first time in a while with: 
```
composer create-project localgovdrupal/localgov-project --stability dev MY_PROJECT
cd MY_PROJECT/
lando start
lando drush si localgov -y
lando composer require localgovdrupal/localgov_core:dev-feature/drupal-10 
lando drush si localgov -y
```
Getting: 

> Adding non-existent permissions to a role is not allowed. The incorrect permissions are "create document media", "create image media", "create remote_video media", "delete own document media", "delete own image media", "delete own remote_video media",  
>    "edit any document media", "edit any image media", "edit any remote_video media", "edit own document media", "edit own image media", "edit own remote_video media".

_Originally posted by @finnlewis in https://github.com/localgovdrupal/localgov/issues/480#issuecomment-1511657363_

**Comment by ekes** [comment]
What jumped into my brain during the meeting.

Can we put stuff that is also in standard _also_ into our profile; and then specific items that are _required_ by our modules _also_ into optional in the localgov_media module and then for anything that has dependencies on anything that might not be installed add the modules installed hooks _as_ _well_.

**Comment by stephen-cox** [comment]
Putting the optional media config in the profile doesn't work. It looks like there's been a change so that optional config is installed later and not with the module.

I have fixed this by forcing the optional config to install when localgov_media is installed.

https://github.com/localgovdrupal/localgov_core/commit/ccbead2556fee2e8bcc18ca946cae6e3a5513404

Will need to check this works with the Standard profile, but at least Drupal 10 site installs are working again

**Comment by stephen-cox** [comment]
Closing as we have D10 support working
