### ISSUE TITLE
Previewing more than a single page at a time

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#600]
Preview links only work for single pages. This means editors have to send multiple links to service colleagues for them to check guides, step by step, directories, whole content sections... it's not ideal

In Cumbria we got around this issue using separate environments, and Entity Share to push content between them https://cumbria.localgov.blog/2022/05/31/using-entity-share-with-localgov-drupal/

This may not be practical for many councils. It would be good to explore options

**Comment by willguv** [comment]
Big issue for Essex - also inconsistent about what's shown. A big issue for stakeholders who're being asked a lot of "an email with 20 links isn't helping"

Also more urgent than other issues as content reviewing is happening all the time

Haringey has a single read only log in to workaround this

Newcastle uses Entity Share

Content designers can share a variety of content types from single guides to whole sections, so solution needs to work for all scenarios

**Comment by andybroomfield** [comment]
Is also an issue at BHCC, we have used the login with limited role in the past.
Does entity share require a seperate provisoned environment just for testing?
That might be impractical. Would it be possible to extend preview link or create a new module that grants access to a limited set of pages? Maybe setting as a cookie instead of long links??

**Comment by willguv** [comment]
Hi Andy, yes Entity Share requires a separate environment - agree that this isn't practical for a lot of councils. It was very useful for us in Cumbria though

I'd like us to look at extending preview link functionality or creating something new

Can't do Product Group today sadly (you should have a cancellation) but am catching up with Stephen soon to talk about this and a few other issues. Can invite you?

**Comment by willguv** [comment]
Wondering if we could add another workflow state "Accuracy check" which can only be viewed by a user with limited permissions

Then create a single user account with this role, and details can be shared with services

Thinking aloud here...

**Comment by willguv** [comment]
Easiest - provide a "Service contact" read only login, as Haringey has done. Users would be able to view all unpublished content, but we don't think this is too big an issue. Users would have to find their content again

Also talk at Tech Group about options @finnlewis @andybroomfield @stephen-cox 

---
Other options

Workflow access - a way of restricting view of unpublished content (eg by url or entry in services menu) . Provide documentation on config options

Workspace - could be created for staging etc or for a single guide which could be shared with a service contact

https://www.drupal.org/project/workspace

**Comment by willguv** [comment]
Andy: 

Brighton takes read only login approach, and also sometimes publishes on staging environment. Looking at Entity Share

BHCC comms like the temporary link idea, but needs to work for multiple pages

Thoughts:

- Is there a way of setting a cookie with the extra string of characters attached to a url?
- Or limit what a user can see using workflow access?
- Or pair with the service contact notifications work?

Need to make sure the public can't discover the log in screen as they'll try to log in with MyAccount

**Comment by Adnan-cds** [comment]
> I'd like us to look at extending preview link functionality or creating something new

Yeah, that's what I was thinking.  This is how it should work:
- Editor shares the preview link for a Guide overview page (or service landing page or directory channel page or something like that).
- Some custom code converts all URLs on the Guide overview page.  This means if there is a link for */a/guide/page*, it will become */preview-link/a/guide/page/VERY-LONG-TOKEN-GOES-HERE*.  The localgov_moderngov module does a [similar URL modification](https://github.com/localgovdrupal/localgov_moderngov/blob/fc4b619d06389d3e12bd59a0cbe05ba5e03e4bcb/src/EventSubscriber/HtmlResponseSubscriber.php#L57) which could be relevant.
- When a request for a **Guide page** belonging to the previewed Guide overview page arrives later, some custom code determines its parent page i.e. the Guide overview page.
- If the preview token which is part of the Guide page path applies to the **parent** Guide overview page, access is allowed.  This will need some custom access checker code.

Example:
- Editor shares link for /preview-link/node/10/VERY-LONG-TOKEN.
- When /preview-link/node/10/VERY-LONG-TOKEN is viewed, all links on the page are converted to this format: /preview-link/Existing/URL/VERY-LONG-TOKEN.  Example: /preview-link/node/22/VERY-LONG-TOKEN
- When /preview-link/node/22/VERY-LONG-TOKEN is viewed, we determine if there is a parent.  Turns out there is a parent and that is node 10.  This node 10 is our Guide overview page.
- We see if VERY-LONG-TOKEN applies to node 10 for preview purposes.  If yes, we allow access to /preview-link/node/22/VERY-LONG-TOKEN.

I must say I haven't tried anything like this.  The whole thing may not work or prove too complex.

**Comment by willguv** [comment]
Thanks @Adnan-cds 

Any thoughts @andybroomfield @stephen-cox @finnlewis? Worth chatting about it at the Tech Group too?

**Comment by willguv** [comment]
@stephen-cox separately, could we specify a new read only "Service contact" role to go along with the Service contact work you're doing elsewhere?

Is this a lot of effort?

**Comment by andybroomfield** [comment]
It might be a bit simpler than rewriting links, just using `hook_node_access` and then maybe using either condition field or entity references to determine whats allowed. Theres also the issue of nodes that are linked into landing pages but not yet published so they don't show on landing pages unless you have permission to view them.

Its something to think about and possibly worth those interested getting heads together post Drupal 10 to work out the best approach.

**Comment by markconroy** [comment]
Anyone tried the "Preview Site" module? Looks like it might do what we want here and is created by the same developers as the Preview Link module.

https://www.drupal.org/project/preview_site

However, it does add Tome and other modules to the site as well as preview_site itself, so might be a heavy duty piece of work.

**Comment by stephen-cox** [comment]
> @stephen-cox separately, could we specify a new read only "Service contact" role to go along with the Service contact work you're doing elsewhere?
> 
> Is this a lot of effort?

@willguv This shouldn't be a lot of work, but as it's a self contained task I would suggest creating a separate issue for this. There's already too much stuff going on on the [email notification issue](https://github.com/localgovdrupal/localgov_workflows/issues/12) and it's possible for someone else to pick up if they get to before I do.

**Comment by stephen-cox** [comment]
> Anyone tried the "Preview Site" module? Looks like it might do what we want here and is created by the same developers as the Preview Link module.

This has an interesting approach to this issue:

> Extends the paradigm of the [Preview link](https://www.drupal.org/project/preview_link) module to the concept of previewing more than one item of content, by way of a static site.

It looks to create a static site for each preview. I doubt this is a simple drop-in solution though as there's going to be some hosting setup needed to allow multiple previews to be deployed. I would also imagine creating a static copy of a large site is going to be quite time  consuming and resource hungry. Could be worth evaluating through.

**Comment by finnlewis** [comment]
What about recommending using workspaces for this sort of thing? 

Workspaces is part of Drupal core experimental, but I've tested it with guides and step-by-step and it works. 

https://www.drupal.org/docs/8/core/modules/workspace/overview

I did run into some problem with subsites, but I'm sure we could work through issues if we wanted to go this route.

I wonder if/how preview link would work with workspaces.... ?

**Comment by markconroy** [comment]
@finnlewis workspaces sounds like a very good idea and definitely worth some investigation.

**Comment by andybroomfield** [comment]
We'd also need to check how this works with caching, as if we used the same urls and a CDN or varnish cache is in use it might be that pages that anon users browse get saved to serve all anon traffic so there is potential for data leakage.

I like the approach of creating a static preview, but it should limit it to just the pages being previewed as otherwise there will be 1000s of pages generated, the use case is previewing a section as it would appear when published, so a way of bundling a set of pages or everything under this page, if the module linked above can do that.

**Comment by andybroomfield** [comment]
So reading it more closely

> Content editors can create unlimited preview sites - each site consists of one or more pieces of draft content they wish to share with non-authenticated users to preview before publishing

**Comment by andybroomfield** [comment]
This is what the admin screen for preview site module looks like, would be nice if it could use wildcard urls.

![screencapture-bhcclocalgov-test-admin-structure-preview-site-builds-1-edit-2023-12-08-13_48_58](https://github.com/localgovdrupal/localgov/assets/1467480/fc0074cc-9f4c-4d86-b22b-8ee794da52ee)

It then builds a static site, but (at least in default config, havnt dived into settings yet) the links are all back to the main site.

<img width="1408" alt="Screenshot 2023-12-08 at 1 53 02 pm" src="https://github.com/localgovdrupal/localgov/assets/1467480/61f0961a-1d54-47a4-877e-3f690554550f">

**Comment by markconroy** [comment]
This looks very promising. Thanks @andybroomfield

**Comment by willguv** [comment]
Hi @andybroomfield @finnlewis @markconroy @stephen-cox it would be good to restart the conversation about this as it's still amongst the most wanted fixes for content editors - just discussed again in a content session

**Comment by willguv** [comment]
Preview Site looks like the best for non authenticated users - see Andy's demo above

x What infrastructure is required?
x What technical support would councils need to install and use?
x Have to specify every individual item to be included in the Preview Site

**Comment by Adnan-cds** [comment]
> It might be a bit simpler than rewriting links, just using hook_node_access and then maybe using either condition field or entity references to determine whats allowed. 

On a form dev site, I am using the newest preview_link which is version [2.1.0-alpha2](https://www.drupal.org/project/preview_link/releases/2.1.0-alpha2) and this may have implemented something like the above.  This is how it works:
- Add all unpublished child Guide pages to a preview link for a Guide overview page.
- Open the preview link for the Guide overview page.
- Click any of the Guide page links on the previewed page.
- The Guide page opens and says it is available only because of the preview link.

Screenshot of the preview link form follows: 
![screenshot-preview-link-edit-form](https://github.com/localgovdrupal/localgov/assets/50206849/e36e3db1-1d45-4cdf-9360-f3027bb0194c)

Not bad :)

**Comment by willguv** [comment]
@stephen-cox please install on Product site - thank you!

**Comment by andybroomfield** [comment]
Require a config option (can't find it in the UI) for `preview_link.settings.yml` set the key `multiple_entities: true`

**Comment by stephen-cox** [comment]
@willguv This is now on the product site.  You can now add extra content when generating a preview link.

It looks like we'll need to make some changes to accommodate it though. This is an unpublished guide overview: https://product.localgovdrupal.org/preview-link/node/120/755882c3-d07f-4dca-8bbd-5d18f7348efb

The guide pages are not in the navigation even though they are accessible:

* https://product.localgovdrupal.org/preview-link/node/121/755882c3-d07f-4dca-8bbd-5d18f7348efb
* https://product.localgovdrupal.org/preview-link/node/122/755882c3-d07f-4dca-8bbd-5d18f7348efb

**Comment by willguv** [comment]
@stephen-cox this looks promising - thank you!

When clicking "Preview link" for a Guide overview, are all the linked guide pages automatically populated in the entities list?

I think we should remove the Drupal-isms. The content group can help with new wording

Is it possible to include a control to vary the expiry time (either per link or somewhere in config?)

What else would we need to do please?

**Comment by stephen-cox** [comment]
> When clicking "Preview link" for a Guide overview, are all the linked guide pages automatically populated in the entities list?

It's a manual job to add all the links you want to preview. We could build a form to do this automatically for things like guides and step by steps, but it would a chunk of work.

> Is it possible to include a control to vary the expiry time (either per link or somewhere in config?)

This can be configured at a global level; not on a given page. As [discussed in Slack](https://localgovdrupal.slack.com/archives/CSS2YS6BW/p1707381933895689) there's no UI for setting this, although patching the module to add a config form should be easy enough.

> What else would we need to do please?

To release this as is, it's just a matter of turning it on for new sites and documenting how to do it for existing sites.

**Comment by willguv** [comment]
@stephen-cox patch the module to provide an UI for:

- switching the module on and off
- changing the expiry time

**Comment by willguv** [comment]
@stephen-cox could we talk at today's PG about the work involved to provide a form to add all guides/ step by step assets to a preview link automatically?

Would be good to get an estimate

We think around a day's work, followed by technical review

Let's check out why it's an Alpha

If urgent need, devs can turn on the Alpha version via the command line

**Comment by stephen-cox** [comment]
PR adding the admin UI which will allow sites to turn on previewing of multiple pages here: https://github.com/localgovdrupal/localgov/pull/691

**Comment by willguv** [comment]
Could you demo this at the next PG @stephen-cox please?

**Comment by willguv** [comment]
About 10 hours work

Ideally should include:
- directories
- step by step
- guide
- subsites
- HTML pubs?

Consider size of each above, maybe needs guidance

**Comment by stephen-cox** [comment]
@willguv There are pull / merge requests for all this here:

* https://git.drupalcode.org/project/preview_link/-/merge_requests/28
* https://github.com/localgovdrupal/localgov/pull/713
* https://github.com/localgovdrupal/localgov_guides/pull/163
* https://github.com/localgovdrupal/localgov_step_by_step/pull/98

**Comment by willguv** [comment]
See this in action at https://www.youtube.com/watch?v=rCREsyceNBw

**Comment by Dixonj1** [comment]
@stephen-cox I've created a preview link for a guide that has 11 pages. I clicked 'Add all pages to this guide' and [when I view this preview link logged in](https://www.wirral.gov.uk/preview-link/node/11905/fe929db5-5c1b-4689-aa24-91909d3e5109) I can see all the pages. When I'm logged out I can only see the first page. Does it only work for users who are logged in? Most colleagues I use this with will not have an account on the website.
