### ISSUE TITLE
3.x stable release blockers

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov#635]
Discussing release blockers to a stable 3.x release.

@andybroomfield suggests at a minimum we want to ensure stable releases of our major projects. 

- [x] LocalGov Directories https://github.com/localgovdrupal/localgov/blob/3.x/composer.json#L28
- [x] LocalGov Events https://github.com/localgovdrupal/localgov/blob/3.x/composer.json#L29
- [x] LocalGov Geo: https://github.com/localgovdrupal/localgov_geo/issues/100 
- [x] LocalGov Paragraphsl https://github.com/localgovdrupal/localgov_paragraphs/pull/155
- [x] Localgov profile fix upgrade test PR #637
- [x] Lovalgov profile release PR #636 

_edited by @andybroomfield on 07/11/2023 to include paragraphs and profile_

**Comment by finnlewis** [comment]
We've released localgov_geo, just need to do the same for directories and events.

@andybroomfield is taking a look!

**Comment by andybroomfield** [comment]
Directories PR to set localgov_geo at 2.0 https://github.com/localgovdrupal/localgov_directories/pull/323
Events PR to set localgov_geo at 2.0 https://github.com/localgovdrupal/localgov_events/pull/129

Directories has a test failure due to an issue with localgov paragraphs, I have a PR for that here https://github.com/localgovdrupal/localgov_paragraphs/pull/155

There is also the test failure in the [profile beta PR](https://github.com/localgovdrupal/localgov/pull/636)

> 1) Drupal\Tests\localgov\Functional\LocalGovUpdateTest::testUpdate
> [19](https://github.com/localgovdrupal/localgov/actions/runs/6694386451/job/18420083087#step:5:20)
> The link Continue was not found on the page.
> [20](https://github.com/localgovdrupal/localgov/actions/runs/6694386451/job/18420083087#step:5:21)
> Failed asserting that an array has the key 0.
> [21](https://github.com/localgovdrupal/localgov/actions/runs/6694386451/job/18420083087#step:5:22)

**Comment by andybroomfield** [comment]
- Localgov demo https://github.com/localgovdrupal/localgov_demo
Could also use a full release, I don't know if there are any blockers though?

**Comment by andybroomfield** [comment]
We released it!
