### ISSUE TITLE
PHP notice in View creation page

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov#70]
**Location**: /admin/structure/views/add
**Message**: Notice: Undefined index: target_bundles in Drupal\node\Plugin\views\wizard\Node->buildFilters() (line 307 of core/modules/node/src/Plugin/views/wizard/Node.php). ...
**Screenshot**: ![screenshot-views-add-error-msg](https://user-images.githubusercontent.com/50206849/84271460-09371a80-ab24-11ea-9fde-5451e85764c1.png)
**How to reproduce**: Just open /admin/structure/views/add

Minor issue.

**Comment by andybroomfield** [comment]
I am still experincing this issue. Sounds quite a bug as many site builders will be building views. This needs to be addressed.

**Comment by andybroomfield** [comment]
Related bug? https://www.drupal.org/project/drupal/issues/3044727

**Comment by andybroomfield** [comment]
Debugging gave me this with localgov_topic_classified
````
Array
(
    [view] => Array
        (
            [view_name] => topics
            [display_name] => entity_reference_2
            [arguments] => Array
                (
                )

        )

)
````
So is localgov_topics_classified used anywhere, and has no target bundles set?

**Comment by andybroomfield** [comment]
Looking into BHCC code, we have the following added to core/modules/node/src/Plugin/views/wizard/Node.php
````php
if (isset($handler_settings['target_bundles'])) {
  $target_bundles = $handler_settings['target_bundles'];
}
````
Its from a patch on https://www.drupal.org/project/drupal/issues/3069925 which is now marked as fixed so is quite possibly fixed in latest Drupal 9 branch.

You can also change localgov_topics_classified to the default method for referenced entities instead of using a view which also resolves this.
