### ISSUE TITLE
Quick copy button for preview links

### ISSUE THREAD

**Issue by ElizabethPace** [localgovdrupal/localgov#722]
Hi. 

Is it possible to have a quick copy button for preview links? Would save having to click and highlight the link and Ctrl C.

Something similar to YouTube or the 2 squares copy icon?

Thanks.

![PreviewCopy](https://github.com/localgovdrupal/localgov_base/assets/131793219/1fd960c3-1cee-41ec-99df-86c8818fcedd)

**Comment by andybroomfield** [comment]
Could be worth looking at [Clipboard js module](https://www.drupal.org/project/clipboardjs) and seeing if that template is modifiable.

Right clicking the link should get you the option to copy the link for now.

**Comment by markconroy** [comment]
Hi @ElizabethPace.

Thanks for posting this issue, I think it's a great idea. 

I'm going to create a patch for this for the main Drupal module rather than just LocalGov Drupal, so all users of the Preview Link module can benefit from it.

If it's accepted there, great. If not, I'll do a local version of it just for LGD.

Here's 2 screenshots of what I have worked out so far:

![Screenshot 2024-05-22 at 14 54 30](https://github.com/localgovdrupal/localgov_base/assets/2183332/78e0e851-4eb5-463b-a6e3-94b027ebc92f)

![Screenshot 2024-05-22 at 14 54 38](https://github.com/localgovdrupal/localgov_base/assets/2183332/4724b056-3031-444d-b4b9-240eab4ceae3)

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

**Comment by ElizabethPace** [comment]
Hi Mark

This looks great. Thank you.

On the 'Preview link copied to clipboard' message, is it possible that the message is just shown for 5 seconds and then disappears  (like on YouTube) so the user doesn't have to click 'OK'?

**Comment by markconroy** [comment]
Here's the PR for this on Drupal.org - https://www.drupal.org/project/preview_link/issues/3449121

I've changed the working of it a little now, so when you click on "Copy link to clipboard", the text changes to "Copied!" for 2 seconds, then back to the default text.

![Screenshot 2024-05-22 at 17 01 21](https://github.com/localgovdrupal/localgov_base/assets/2183332/6d0a2bfb-0c8c-46f6-a1c0-b71f395fd4f0)


===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

**Comment by willguv** [comment]
Love this idea, thanks both!

**Comment by ElizabethPace** [comment]
Brilliant! Thanks a lot @markconroy

**Comment by markconroy** [comment]
While we are waiting on the patch to be reviewed/committed on Drupal.org, here's the same patch for us to use in the meantime.

https://github.com/localgovdrupal/localgov/pull/723

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.
